# Generated by Django 4.0.6 on 2022-08-01 21:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('q_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Monument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('q_number', models.CharField(max_length=200, unique=True)),
                ('wlm_n', models.CharField(blank='', default='', max_length=200)),
                ('start_n', models.DateTimeField(blank=True, null=True)),
                ('end_n', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(default=dict)),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('first_revision', models.DateTimeField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('poly', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('complete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('region_code', models.IntegerField()),
                ('poly', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=200, unique=True)),
                ('image_url', models.URLField(max_length=2000)),
                ('image_date', models.DateTimeField(blank=True, null=True)),
                ('image_type', models.CharField(max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('monument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.monument')),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('province_code', models.IntegerField()),
                ('region_code', models.IntegerField()),
                ('poly', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.province')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region')),
            ],
        ),
        migrations.CreateModel(
            name='MonumentAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized', models.BooleanField()),
                ('event_date', models.DateField()),
                ('data', models.JSONField(default=dict)),
                ('monument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.monument')),
            ],
        ),
        migrations.AddField(
            model_name='monument',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monuments', to='main.municipality'),
        ),
        migrations.AddField(
            model_name='monument',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monuments', to='main.province'),
        ),
        migrations.AddField(
            model_name='monument',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monuments', to='main.region'),
        ),
        migrations.AddField(
            model_name='monument',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monuments', to='main.snapshot'),
        ),
        migrations.CreateModel(
            name='CategorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('payload', models.JSONField(default=None, null=True)),
                ('complete', models.BooleanField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_snapshots', to='main.snapshot')),
            ],
        ),
    ]
