# Generated by Django 4.0.6 on 2022-08-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorysnapshot',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
