# Generated by Django 4.0.6 on 2022-07-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monument',
            name='code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
