# Generated by Django 4.0.6 on 2022-08-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_categorysnapshot_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='image_title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='categorysnapshot',
            name='payload',
            field=models.JSONField(default=None, editable=False, null=True),
        ),
    ]
