# Generated by Django 4.0.6 on 2022-07-31 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_monument_end_n_monument_start_n_monument_wlm_n'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monument',
            old_name='name',
            new_name='label',
        ),
    ]
