# Generated by Django 4.0.6 on 2022-07-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_name_monument_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monument',
            name='end_n',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monument',
            name='start_n',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
