# Generated by Django 4.0.6 on 2022-07-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_monument_end_n_alter_monument_start_n'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('q_number', models.CharField(max_length=200, unique=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='monument',
            old_name='code',
            new_name='q_number',
        ),
    ]
