# Generated by Django 4.0.6 on 2022-07-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_categorysnapshot_rename_code_monument_q_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorysnapshot',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
