# Generated by Django 4.0.6 on 2022-07-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_monument_municipality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='event_date',
        ),
        migrations.AddField(
            model_name='picture',
            name='image_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='image_id',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
