# Generated by Django 4.0.6 on 2022-08-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_monument_end_alter_monument_first_revision_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='monument',
            index_together=set(),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
