# Generated by Django 4.0.6 on 2022-07-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_picture_event_date_picture_image_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='type',
            new_name='image_type',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='image',
            new_name='image_url',
        ),
        migrations.AlterField(
            model_name='picture',
            name='image_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
