# Generated by Django 4.0.6 on 2022-07-31 12:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_type_picture_image_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='poly',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
