# Generated by Django 4.0.6 on 2022-07-31 12:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_region_poly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='poly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
