# Generated by Django 4.0.6 on 2022-08-31 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_picture_index_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='monument',
            index_together={('id', 'start', 'first_revision')},
        ),
    ]
