# Generated by Django 4.0.6 on 2022-07-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_region_poly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='data',
        ),
        migrations.AddField(
            model_name='municipality',
            name='code',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='province',
            name='code',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='code',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
