# Generated by Django 4.0.6 on 2022-08-31 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_monument_index_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='monument',
            index_together={('start', 'first_revision', 'first_image_date'), ('start', 'first_revision')},
        ),
    ]
