# Generated by Django 4.0.6 on 2022-07-31 12:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_municipality_province_code_municipality_region_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='data',
        ),
        migrations.RemoveField(
            model_name='province',
            name='data',
        ),
        migrations.AddField(
            model_name='municipality',
            name='poly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='province',
            name='poly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
