# Generated by Django 4.0.6 on 2022-07-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_municipality_data_remove_province_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.IntegerField(),
        ),
    ]
