# Generated by Django 4.0.6 on 2022-07-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_region_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='province_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='region_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='province',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='province',
            name='region_code',
            field=models.IntegerField(),
        ),
    ]
