# Generated by Django 4.0.6 on 2022-09-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_category_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monument',
            name='wlm_n',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
