# Generated by Django 4.0.6 on 2022-10-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_monument_wlm_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='current_commons_state',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='monument',
            name='current_wlm_state',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
