# Generated by Django 4.0.6 on 2022-07-31 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_monument_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.province'),
        ),
        migrations.AddField(
            model_name='monument',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region'),
        ),
    ]
