# Generated by Django 4.0.6 on 2022-10-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_monument_current_commons_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='csv_export',
            field=models.FileField(blank=True, null=True, upload_to='csv_exports'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='xlsx_export',
            field=models.FileField(blank=True, null=True, upload_to='xlsx_exports'),
        ),
    ]
