# Generated by Django 4.0.6 on 2022-10-18 21:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_snapshot_csv_export_snapshot_xlsx_export'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalityLookup',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('province_code', models.IntegerField()),
                ('region_code', models.IntegerField()),
                ('poly', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
