# Generated by Django 4.0.6 on 2022-07-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_monument_province_monument_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('q_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='monument',
            name='categories',
            field=models.ManyToManyField(blank=True, to='main.category'),
        ),
    ]
