# Generated by Django 4.0.6 on 2022-07-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_category_monument_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image_url',
            field=models.URLField(max_length=2000),
        ),
    ]
