# Generated by Django 4.0.6 on 2022-10-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_picture_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monument',
            name='first_image_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='monument',
            name='first_image_date_commons',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
