# Generated by Django 4.0.6 on 2022-07-31 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_picture_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snapshot',
        ),
        migrations.AddField(
            model_name='monument',
            name='first_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monument',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monuments', to='main.municipality'),
        ),
        migrations.AlterField(
            model_name='monument',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monuments', to='main.province'),
        ),
        migrations.AlterField(
            model_name='monument',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monuments', to='main.region'),
        ),
    ]
