# Generated by Django 4.0.6 on 2022-10-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_monument_first_image_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='pictures_commons_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monument',
            name='pictures_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monument',
            name='pictures_wlm_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monument',
            name='to_review',
            field=models.BooleanField(default=False),
        ),
    ]
