# Generated by Django 4.0.6 on 2022-07-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_delete_snapshot_monument_first_revision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='id',
        ),
        migrations.AlterField(
            model_name='municipality',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
