# Generated by Django 4.0.6 on 2022-12-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_monument_pictures_commons_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='approved_by',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
