# Generated by Django 4.0.6 on 2022-07-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_municipality_id_alter_municipality_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='id',
        ),
        migrations.AlterField(
            model_name='province',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
