# Generated by Django 4.0.6 on 2022-07-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_province_id_alter_province_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='id',
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
