# Generated by Django 4.0.6 on 2022-12-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20221205_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='most_recent_commons_image_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monument',
            name='most_recent_wlm_image_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
