# Generated by Django 4.0.6 on 2023-07-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_monument_most_recent_commons_image_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='in_contest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monument',
            name='relevant_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
