# Generated by Django 4.0.6 on 2023-07-12 09:18

from django.db import migrations

def fix_in_contest(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Monument = apps.get_model("main", "Monument")
    for monument in Monument.objects.all():
        
        if not monument.start:
            monument.in_contest = False
            continue

        if monument.start and not monument.end:
            monument.in_contest = True
        else:
            monument.in_contest = monument.end < monument.start
        
        monument.save()
         



class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_monument_in_contest_alter_monument_relevant_images'),
    ]

    operations = [
        migrations.RunPython(fix_in_contest),
    ]
