# Generated by Django 4.0.6 on 2023-07-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_appcategory_category_app_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appcategory',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
