# Generated by Django 4.0.6 on 2023-08-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_monumentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='article',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
