# Generated by Django 4.0.6 on 2023-08-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_monument_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='monument',
            name='admin_entity',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
