# Generated by Django 4.0.6 on 2023-08-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_monument_address_monument_admin_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='is_relevant',
            field=models.BooleanField(default=False),
        ),
    ]
