# Generated by Django 4.0.6 on 2023-08-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_date',
            field=models.DateField(),
        ),
    ]
