# Generated by Django 4.0.6 on 2023-08-21 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_monument_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySnapshotError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_query', models.TextField()),
                ('error', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='main.snapshot')),
            ],
        ),
    ]
