# Generated by Django 4.0.6 on 2023-08-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_categorysnapshoterror'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appcategory',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='contest',
            name='label_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
