version: '3'

services:

  wlm_db:
    image: postgis/postgis:13-master
    volumes:
      - ./dockerdata/db:/var/lib/postgresql/data
      - ./dumps:/dumps
    environment:
      #Environment variable for creating DB user and DB
      POSTGRES_USER: wlm
      POSTGRES_PASSWORD: wlm
      POSTGRES_DB: wlm
    restart: always

  wlm_redis:
    image: redis:6.2.6
    restart: always
    volumes:
      - ./dockerdata/redis:/data

  wlm_webserver:
    image: nginx:1.21.4-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dockerdata/server:/data/server
    restart: always
    ports:
      - 80:80
    
  wlm_server:
    image: wikimediait/wlm-server
    restart: always
    command: >
        bash -c "python manage.py collectstatic --noinput
        && python manage.py migrate
        && gunicorn wlm.wsgi --workers=4 --forwarded-allow-ips='*' --bind=0.0.0.0:80 -t 300"
    volumes:
      - ./localsettings.py:/code/wlm/wlm/localsettings.py
      - ./dockerdata/server:/data
      - ./fixtures:/fixtures

  wlm_cronjobber:
    image: wikimediait/wlm-server
    restart: always
    command: cronjobber
    volumes:
      - ./localsettings.py:/code/wlm/wlm/localsettings.py
      - ./dockerdata/server:/data

  wlm_worker:
    image: wikimediait/wlm-server
    restart: always
    command: python manage.py rqworker
    volumes:
      - ./localsettings.py:/code/wlm/wlm/localsettings.py
      - ./dockerdata/server:/data
      

