# Generated by Django 4.0.6 on 2023-08-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_alter_oauth2token_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2token',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='refresh_token',
            field=models.TextField(),
        ),
    ]
