#!/bin/sh

# Ensure the log file exists
touch /logs/crontab.log

# Env for cron
python -c "import os; print('\n'.join([f'{k}=\"{v}\"'for k,v in os.environ.items()]));" >> ~/cronenv

# Added a cronjob in a new crontab
echo "* * * * * /scripts/jobrunner >> /logs/crontab.log 2>&1" > /etc/crontab

# Registering the new crontab
crontab /etc/crontab

# Starting the cron
/usr/sbin/service cron start

# Displaying logs
tail -f /logs/crontab.log & wait