# Generated by Django 4.0.4 on 2022-04-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_time', models.DateTimeField(blank=True, null=True)),
                ('cron_expression', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(max_length=100)),
                ('kwargs', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
