# Generated by Django 4.0.4 on 2022-06-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron_tools', '0002_job_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
